const KANA = [
  { romaji: 'a',  h: 'あ', k: 'ア', group: 'gojuon' },
  { romaji: 'i',  h: 'い', k: 'イ', group: 'gojuon' },
  { romaji: 'u',  h: 'う', k: 'ウ', group: 'gojuon' },
  { romaji: 'e',  h: 'え', k: 'エ', group: 'gojuon' },
  { romaji: 'o',  h: 'お', k: 'オ', group: 'gojuon' },
  { romaji: 'ka', h: 'か', k: 'カ', group: 'gojuon' },
  { romaji: 'ki', h: 'き', k: 'キ', group: 'gojuon' },
  { romaji: 'ku', h: 'く', k: 'ク', group: 'gojuon' },
  { romaji: 'ke', h: 'け', k: 'ケ', group: 'gojuon' },
  { romaji: 'ko', h: 'こ', k: 'コ', group: 'gojuon' },
  { romaji: 'sa', h: 'さ', k: 'サ', group: 'gojuon' },
  { romaji: 'shi', h: 'し', k: 'シ', group: 'gojuon' },
  { romaji: 'su', h: 'す', k: 'ス', group: 'gojuon' },
  { romaji: 'se', h: 'せ', k: 'セ', group: 'gojuon' },
  { romaji: 'so', h: 'そ', k: 'ソ', group: 'gojuon' },
  { romaji: 'ta', h: 'た', k: 'タ', group: 'gojuon' },
  { romaji: 'chi', h: 'ち', k: 'チ', group: 'gojuon' },
  { romaji: 'tsu', h: 'つ', k: 'ツ', group: 'gojuon' },
  { romaji: 'te', h: 'て', k: 'テ', group: 'gojuon' },
  { romaji: 'to', h: 'と', k: 'ト', group: 'gojuon' },
  { romaji: 'na', h: 'な', k: 'ナ', group: 'gojuon' },
  { romaji: 'ni', h: 'に', k: 'ニ', group: 'gojuon' },
  { romaji: 'nu', h: 'ぬ', k: 'ヌ', group: 'gojuon' },
  { romaji: 'ne', h: 'ね', k: 'ネ', group: 'gojuon' },
  { romaji: 'no', h: 'の', k: 'ノ', group: 'gojuon' },
  { romaji: 'ha', h: 'は', k: 'ハ', group: 'gojuon' },
  { romaji: 'hi', h: 'ひ', k: 'ヒ', group: 'gojuon' },
  { romaji: 'fu', h: 'ふ', k: 'フ', group: 'gojuon' },
  { romaji: 'he', h: 'へ', k: 'ヘ', group: 'gojuon' },
  { romaji: 'ho', h: 'ほ', k: 'ホ', group: 'gojuon' },
  { romaji: 'ma', h: 'ま', k: 'マ', group: 'gojuon' },
  { romaji: 'mi', h: 'み', k: 'ミ', group: 'gojuon' },
  { romaji: 'mu', h: 'む', k: 'ム', group: 'gojuon' },
  { romaji: 'me', h: 'め', k: 'メ', group: 'gojuon' },
  { romaji: 'mo', h: 'も', k: 'モ', group: 'gojuon' },
  { romaji: 'ya', h: 'や', k: 'ヤ', group: 'gojuon' },
  { romaji: 'yu', h: 'ゆ', k: 'ユ', group: 'gojuon' },
  { romaji: 'yo', h: 'よ', k: 'ヨ', group: 'gojuon' },
  { romaji: 'ra', h: 'ら', k: 'ラ', group: 'gojuon' },
  { romaji: 'ri', h: 'り', k: 'リ', group: 'gojuon' },
  { romaji: 'ru', h: 'る', k: 'ル', group: 'gojuon' },
  { romaji: 're', h: 'れ', k: 'レ', group: 'gojuon' },
  { romaji: 'ro', h: 'ろ', k: 'ロ', group: 'gojuon' },
  { romaji: 'wa', h: 'わ', k: 'ワ', group: 'gojuon' },
  { romaji: 'wo', h: 'を', k: 'ヲ', group: 'gojuon' },
  { romaji: 'n',  h: 'ん', k: 'ン', group: 'gojuon' },
  { romaji: 'ga', h: 'が', k: 'ガ', group: 'dakuon' },
  { romaji: 'gi', h: 'ぎ', k: 'ギ', group: 'dakuon' },
  { romaji: 'gu', h: 'ぐ', k: 'グ', group: 'dakuon' },
  { romaji: 'ge', h: 'げ', k: 'ゲ', group: 'dakuon' },
  { romaji: 'go', h: 'ご', k: 'ゴ', group: 'dakuon' },
  { romaji: 'za', h: 'ざ', k: 'ザ', group: 'dakuon' },
  { romaji: 'ji', h: 'じ', k: 'ジ', group: 'dakuon' },
  { romaji: 'zu', h: 'ず', k: 'ズ', group: 'dakuon' },
  { romaji: 'ze', h: 'ぜ', k: 'ゼ', group: 'dakuon' },
  { romaji: 'zo', h: 'ぞ', k: 'ゾ', group: 'dakuon' },
  { romaji: 'da', h: 'だ', k: 'ダ', group: 'dakuon' },
  { romaji: 'di', h: 'ぢ', k: 'ヂ', group: 'dakuon' },
  { romaji: 'du', h: 'づ', k: 'ヅ', group: 'dakuon' },
  { romaji: 'de', h: 'で', k: 'デ', group: 'dakuon' },
  { romaji: 'do', h: 'ど', k: 'ド', group: 'dakuon' },
  { romaji: 'ba', h: 'ば', k: 'バ', group: 'dakuon' },
  { romaji: 'bi', h: 'び', k: 'ビ', group: 'dakuon' },
  { romaji: 'bu', h: 'ぶ', k: 'ブ', group: 'dakuon' },
  { romaji: 'be', h: 'べ', k: 'ベ', group: 'dakuon' },
  { romaji: 'bo', h: 'ぼ', k: 'ボ', group: 'dakuon' },
  { romaji: 'pa', h: 'ぱ', k: 'パ', group: 'dakuon' },
  { romaji: 'pi', h: 'ぴ', k: 'ピ', group: 'dakuon' },
  { romaji: 'pu', h: 'ぷ', k: 'プ', group: 'dakuon' },
  { romaji: 'pe', h: 'ぺ', k: 'ペ', group: 'dakuon' },
  { romaji: 'po', h: 'ぽ', k: 'ポ', group: 'dakuon' },
  { romaji: 'kya', h: 'きゃ', k: 'キャ', group: 'yoon' },
  { romaji: 'kyu', h: 'きゅ', k: 'キュ', group: 'yoon' },
  { romaji: 'kyo', h: 'きょ', k: 'キョ', group: 'yoon' },
  { romaji: 'sha', h: 'しゃ', k: 'シャ', group: 'yoon' },
  { romaji: 'shu', h: 'しゅ', k: 'シュ', group: 'yoon' },
  { romaji: 'sho', h: 'しょ', k: 'ショ', group: 'yoon' },
  { romaji: 'cha', h: 'ちゃ', k: 'チャ', group: 'yoon' },
  { romaji: 'chu', h: 'ちゅ', k: 'チュ', group: 'yoon' },
  { romaji: 'cho', h: 'ちょ', k: 'チョ', group: 'yoon' },
  { romaji: 'nya', h: 'にゃ', k: 'ニャ', group: 'yoon' },
  { romaji: 'nyu', h: 'にゅ', k: 'ニュ', group: 'yoon' },
  { romaji: 'nyo', h: 'にょ', k: 'ニョ', group: 'yoon' },
  { romaji: 'hya', h: 'ひゃ', k: 'ヒャ', group: 'yoon' },
  { romaji: 'hyu', h: 'ひゅ', k: 'ヒュ', group: 'yoon' },
  { romaji: 'hyo', h: 'ひょ', k: 'ヒョ', group: 'yoon' },
  { romaji: 'mya', h: 'みゃ', k: 'ミャ', group: 'yoon' },
  { romaji: 'myu', h: 'みゅ', k: 'ミュ', group: 'yoon' },
  { romaji: 'myo', h: 'みょ', k: 'ミョ', group: 'yoon' },
  { romaji: 'rya', h: 'りゃ', k: 'リャ', group: 'yoon' },
  { romaji: 'ryu', h: 'りゅ', k: 'リュ', group: 'yoon' },
  { romaji: 'ryo', h: 'りょ', k: 'リョ', group: 'yoon' },
  { romaji: 'gya', h: 'ぎゃ', k: 'ギャ', group: 'yoon' },
  { romaji: 'gyu', h: 'ぎゅ', k: 'ギュ', group: 'yoon' },
  { romaji: 'gyo', h: 'ぎょ', k: 'ギョ', group: 'yoon' },
  { romaji: 'ja',  h: 'じゃ', k: 'ジャ', group: 'yoon' },
  { romaji: 'ju',  h: 'じゅ', k: 'ジュ', group: 'yoon' },
  { romaji: 'jo',  h: 'じょ', k: 'ジョ', group: 'yoon' },
  { romaji: 'bya', h: 'びゃ', k: 'ビャ', group: 'yoon' },
  { romaji: 'byu', h: 'びゅ', k: 'ビュ', group: 'yoon' },
  { romaji: 'byo', h: 'びょ', k: 'ビョ', group: 'yoon' },
  { romaji: 'pya', h: 'ぴゃ', k: 'ピャ', group: 'yoon' },
  { romaji: 'pyu', h: 'ぴゅ', k: 'ピュ', group: 'yoon' },
  { romaji: 'pyo', h: 'ぴょ', k: 'ピョ', group: 'yoon' },
];

const PHRASES = [
  { jp: 'おはよう', romaji: 'ohayou', cn: '早上好（对熟人）', cat: 'greeting' },
  { jp: 'おはようございます', romaji: 'ohayou gozaimasu', cn: '早上好（礼貌）', cat: 'greeting' },
  { jp: 'こんにちは', romaji: 'konnichiwa', cn: '你好 / 下午好', cat: 'greeting' },
  { jp: 'こんばんは', romaji: 'konbanwa', cn: '晚上好', cat: 'greeting' },
  { jp: 'おやすみなさい', romaji: 'oyasuminasai', cn: '晚安', cat: 'greeting' },
  { jp: 'さようなら', romaji: 'sayounara', cn: '再见', cat: 'greeting' },
  { jp: 'また明日', romaji: 'mata ashita', cn: '明天见', cat: 'greeting' },
  { jp: 'はじめまして', romaji: 'hajimemashite', cn: '初次见面', cat: 'greeting' },
  { jp: 'よろしくお願いします', romaji: 'yoroshiku onegaishimasu', cn: '请多关照', cat: 'greeting' },
  { jp: 'ありがとう', romaji: 'arigatou', cn: '谢谢', cat: 'polite' },
  { jp: 'ありがとうございます', romaji: 'arigatou gozaimasu', cn: '非常感谢', cat: 'polite' },
  { jp: 'すみません', romaji: 'sumimasen', cn: '对不起 / 不好意思', cat: 'polite' },
  { jp: 'ごめんなさい', romaji: 'gomen nasai', cn: '抱歉', cat: 'polite' },
  { jp: 'どういたしまして', romaji: 'dou itashimashite', cn: '不客气', cat: 'polite' },
  { jp: 'お願いします', romaji: 'onegaishimasu', cn: '拜托了 / 请给我', cat: 'polite' },
  { jp: 'はい', romaji: 'hai', cn: '是 / 好的', cat: 'daily' },
  { jp: 'いいえ', romaji: 'iie', cn: '不 / 不是', cat: 'daily' },
  { jp: 'わかりました', romaji: 'wakarimashita', cn: '明白了', cat: 'daily' },
  { jp: 'わかりません', romaji: 'wakarimasen', cn: '不明白', cat: 'daily' },
  { jp: '大丈夫です', romaji: 'daijoubu desu', cn: '没关系 / 没问题', cat: 'daily' },
  { jp: 'お名前は？', romaji: 'onamae wa?', cn: '你叫什么名字？', cat: 'daily' },
  { jp: '〜です', romaji: '~ desu', cn: '我是… / 这是…', cat: 'daily' },
  { jp: 'トイレはどこですか', romaji: 'toire wa doko desu ka', cn: '厕所在哪里？', cat: 'daily' },
  { jp: 'いくらですか', romaji: 'ikura desu ka', cn: '多少钱？', cat: 'daily' },
  { jp: 'おいしい', romaji: 'oishii', cn: '好吃', cat: 'daily' },
  { jp: 'いただきます', romaji: 'itadakimasu', cn: '我开动了（饭前）', cat: 'daily' },
  { jp: 'ごちそうさまでした', romaji: 'gochisousama deshita', cn: '谢谢款待（饭后）', cat: 'daily' },
  { jp: '一', romaji: 'ichi', cn: '1', cat: 'number' },
  { jp: '二', romaji: 'ni', cn: '2', cat: 'number' },
  { jp: '三', romaji: 'san', cn: '3', cat: 'number' },
  { jp: '四', romaji: 'yon / shi', cn: '4', cat: 'number' },
  { jp: '五', romaji: 'go', cn: '5', cat: 'number' },
  { jp: '六', romaji: 'roku', cn: '6', cat: 'number' },
  { jp: '七', romaji: 'nana / shichi', cn: '7', cat: 'number' },
  { jp: '八', romaji: 'hachi', cn: '8', cat: 'number' },
  { jp: '九', romaji: 'kyuu / ku', cn: '9', cat: 'number' },
  { jp: '十', romaji: 'juu', cn: '10', cat: 'number' },
];
